# These are the crop configurations for testing AIBS datasets located at: https://alleninstitute.sharepoint.com/:f:/s/WholeBrainLightsheet/Eg1I6i-X-NFGt-f_Gjhq-zIBxTc42H1_BxKy44rRoKoHHQ?e=Z2T9u0

data: 
    445_sparse:
        zarrs: "s3://aind-open-data/SmartSPIM_696668_2023-10-12_17-50-40_stitched_2023-10-18_21-28-56/image_tile_fusing/OMEZarr/"
        genotype: "wt/wt"
        channel: "Ex_445_Em_469"
        background: "Ex_639_Em_660"
        region:
            - 1920
            - 4224
            - 3840
            - 2176
            - 4480
            - 4096
    488_dense:
        zarrs: "s3://aind-open-data/SmartSPIM_668647_2023-07-18_15-11-55_stitched_2023-10-23_23-24-46/image_tile_fusing/OMEZarr/"
        genotype: "Scl17a7"
        channel: "Ex_488_Em_525"
        background: "Ex_647_Em_690"
        region:
            - 512
            - 4224
            - 5120
            - 768
            - 4480
            - 5376
    488_sparse:
        zarrs: "s3://aind-open-data/SmartSPIM_701850_2024-01-12_12-04-28_stitched_2024-01-13_10-56-32/image_tile_fusing/OMEZarr/"
        genotype: "Oxtr-T2A-Cre"
        channel: "Ex_488_Em_525"
        background: "Ex_639_Em_680"
        region:
            - 2560
            - 1280
            - 2944
            - 2816
            - 1536
            - 3200
    561_sparse:
        zarrs: "s3://aind-open-data/SmartSPIM_714639_2024-02-12_10-19-24_stitched_2024-02-15_10-48-44/image_tile_fusing/OMEZarr/"
        genotype: "wt/mScarlet-10aa-H2B-WPRE3-bGHpA"
        channel: "Ex_561_Em_600"
        background: "Ex_639_Em_680"
        region:
            - 2688
            - 3200
            - 1920
            - 2944
            - 3456
            - 2176
    445_TH1: # Thalamus 445 channel
        genotype: "C57BL6J"
        zarrs: "s3://aind-open-data/SmartSPIM_694513_2023-09-30_00-03-18_stitched_2024-01-11_10-15-23/image_tile_fusing/OMEZarr/"
        channel: "Ex_445_Em_469"
        background: "Ex_639_Em_660"
        region: 
            - 1993
            - 4038
            - 3934
            - 2249
            - 4166
            - 4190
    488_TH2: # Thalamus 488 channel
        zarrs: "s3://aind-open-data/SmartSPIM_694513_2023-09-30_00-03-18_stitched_2024-01-11_10-15-23/image_tile_fusing/OMEZarr/"
        channel: "Ex_488_Em_525"
        background: "Ex_639_Em_660"
        region: 
            - 1993
            - 4038
            - 3934
            - 2249
            - 4166
            - 4190
    561_TH3: # Thalamus 561 channel
        zarrs: "s3://aind-open-data/SmartSPIM_694513_2023-09-30_00-03-18_stitched_2024-01-11_10-15-23/image_tile_fusing/OMEZarr/"
        channel: "Ex_561_Em_593"
        background: "Ex_639_Em_660"
        region: 
            - 2630
            - 4256
            - 5340
            - 2886
            - 4384
            - 5596
    488_HY1: # Hypothalamus
        zarrs: "s3://aind-open-data/SmartSPIM_699316_2023-12-06_16-14-29_stitched_2023-12-07_11-57-29/image_tile_fusing/OMEZarr/"
        channel: "Ex_488_Em_525"
        background: "Ex_639_Em_667"
        region: 
            - 3202
            - 3761
            - 4106
            - 3458
            - 4017
            - 4362
    488_HY2: # Hypothalamus with tissue edge
        zarrs: "s3://aind-open-data/SmartSPIM_724016_2024-05-13_17-12-24_stitched_2024-05-15_12-02-36/image_tile_fusing/OMEZarr/"
        channel: "Ex_488_Em_525"
        background: "Ex_639_Em_667"
        region: 
            - 3000
            - 5000
            - 4050
            - 3256
            - 5256
            - 4306   
