# These are the crop configurations for testing AIBS datasets located at: https://alleninstitute.sharepoint.com/:f:/s/WholeBrainLightsheet/Eg1I6i-X-NFGt-f_Gjhq-zIBxTc42H1_BxKy44rRoKoHHQ?e=Z2T9u0

data: 
    445_sparse:
        zarrs: "/data/SmartSPIM_696668_2023-10-12_17-50-40_stitched_2023-10-18_21-28-56/image_tile_fusing/OMEZarr/"
        genotype: "wt/wt"
        channel: "Ex_445_Em_469"
        background: "Ex_639_Em_660"
        region:
            - 1920
            - 4224
            - 3840
            - 2176
            - 4480
            - 4096
zarr_params:
    resolution:
        - 1.0
        - 1.0
        - 2.0
        - 1.8
        - 1.8
    axes_order:
        - "t"
        - "c"
        - "z"
        - "y"
        - "x"
    units:
        - "millisecond"
        - None
        - "micrometer"
        - "micrometer"
        - "micrometer"
    types:
        - "time"
        - "channel"
        - "space"
        - "space"
        - "space"
    levels: 3
save_path: "/results"
bucket: "102-01-001-10_MCT"
s3_path: "SmartSPIM_benchmark_datasets"
